app1/urls.py
from django.urls import path
from app1.views import *

app_name='something'

urlpatterns=[
    path('unknown/',unknown,name='unknown'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='nothing'

urlpatterns=[
    path('response/',response,name='response'),
]

specific_url_nav/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def unknown(request):
    return render(request,'unknown.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def response(request):
    return render(request,'response.html')

templates/response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>There is nothing to say more than this...</h1>
        <h1>Chadhuvukondi Firstuuu....</h1>
        <a href="{% url 'something:unknown' %}"><h1>Navigating to Unknown page</h1></a>
    </center>
</body>
</html>

templates/unknown.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>I'm unknown person looking for someone...</h1>
        <a href="{% url 'nothing:response' %}"><h1>for response click here</h1></a>
    </center>
</body>
</html>